baseURL = "https://tuansonnn.github.io/tagging-workshop/"
languageCode = "en-us"
title = "Create a new AWS account."
theme = "hugo-theme-learn"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  author = "journeyoftheaverageguy@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[Languages]
  [Languages.en]
    title = "Create a new AWS account."
    weight = 1
    languageName = "English"
  [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
    identifier = "AWS Study Group"
    url = "https://aws.amazon.com/blogs"
    weight = 20
